title: Vresod's website
email: luke@vresod.tk
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Vresod, and I like programming. This is my website.
twitter_username: lukeeidek
github_username:  vresod

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - CNAME
  - README.md
